name: Format Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format-code-base:
    runs-on: ubuntu-latest

    steps:
      - name: 💽 Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 💅 Run Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{md,sh}
          prettier_plugins: "prettier-plugin-sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
